Sitegeist:
  LostInTranslation:
    DeepLApi:

      #
      # This package needs an authenticationKey for the DeeplL Api from https://www.deepl.com/pro-api.
      # There are free plans that support a limited number but for productive use we recommend using a payed plan.
      #
      authenticationKey: ''

      #
      # Glossary management
      #
      glossary:
        #
        # The label prefix can be used to prevent different instances overwriting or deleting each other
        # glossaries. The default value is the FLOW_CONTEXT but this may need adjustment based on your use case
        #
        labelPrefix: '%env:FLOW_CONTEXT%'
        #
        # The number of outdated remote glossaries to keep to reduce problems when systems are cloned
        #
        keepNumber: 10

      defaultOptions:
        tag_handling: 'xml'
        split_sentences: 'nonewlines'
        preserve_formatting: 1
        formality: 'default'
        ignore_tags: 'ignore'

      #
      # Here you can define terms that will be wrapped with an <ignore> tag
      # and hence ignored by the DeepL API.
      # For example: brand names, city names, etc.
      #
      ignoredTerms: []

      #
      # Here you can specify how a request to the DeepL API should
      # be attempted. Any number higher than 1 means that there will be
      # retries.
      #
      # 1 = one attempt
      # 2 = two attempts
      # and so on...
      #
      numberOfAttempts: 1

      #
      # Here you can optionally disable the translation cache,
      # see README for more information.
      # BEWARE: disabling this cache while using the Eel Helper
      # can significantly slow down your page or even
      # lead to timeouts. Use with care!
      #
      enableCache: true

    nodeTranslation:
      #
      # Enable the automatic translations of nodes while they are adopted to another dimension
      #
      enabled: true

      #
      # Translate all inline editable fields without further configuration.
      #
      # If this is disabled inline editables can be configured for translation by setting
      # `options.automaticTranslation: true` for each property separately
      #
      translateInlineEditables: true

      #
      # The name of the content repository to fetch dimension configurations from
      #
      contentRepositoryIdentifier: 'default'

      #
      # The name of the language dimension. Usually needs no modification
      #
      languageDimensionName: 'language'

      #
      # Translate all object properties that have a translationConnector configured
      # if this is set to false each property must be enabled via options.automaticTranslation
      #
      translateTypesWithConnectors: true

      #
      # Connectors to translate value object properties
      #
      # for each value object type a class implementing the TranslationConnectorInterface
      # can be configured to extract and apply translations
      #
      translationConnectors: []

      #
      # Apply html_entity_decode to translated strings.
      # !!! this is experimental and may be removed in future !!!
      #
      experimental-applyHtmlEntityDecodeAfterTranslation: false
