Neos:
  Fusion:
    defaultContext:
      'Sitegeist.LostInTranslation': 'Sitegeist\LostInTranslation\Eel\TranslationHelper'
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Sitegeist.LostInTranslation':
            - '*'
