Neos:
  Fusion:
    defaultContext:
      'Sitegeist.LostInTranslation': 'Sitegeist\LostInTranslation\Eel\TranslationHelper'
  Neos:
    fusion:
      autoInclude:
        'Sitegeist.LostInTranslation': true
    modules:
      management:
        submodules:
          sitegeist_lostintranslation:
            label: 'Lost In Translations'
            description: 'DeepL based Translations for Neos'
            icon: 'icon-language'
            controller: 'Sitegeist\LostInTranslation\Controller\LostInTranslationModuleController'
            privilegeTarget: 'Sitegeist.LostInTranslation:AccessBackendModule'

  ContentRepositoryRegistry:
    presets:
      'default':
#        contentGraphProjection:
#          catchUpHooks:
#            'Sitegeist.LostInTranslation:TranslationCatchupHook':
#              factoryObjectName: Sitegeist\LostInTranslation\ContentRepository\CatchUpHook\TranslationCatchupHookFactory
        commandHooks:
          'Sitegeist.LostInTranslation:TranslationCommandHook':
            factoryObjectName: Sitegeist\LostInTranslation\ContentRepository\CommandHook\TranslationCommandHookFactory
