Neos:
  Fusion:
    defaultContext:
      'Sitegeist.LostInTranslation': 'Sitegeist\LostInTranslation\Eel\TranslationHelper'
  Neos:
    modules:
      management:
        submodules:
          sitegeist_lostintranslation:
            label: 'Sitegeist.LostInTranslation:Modules:module.label'
            description: 'Sitegeist.LostInTranslation:Modules:module.description'
            icon: 'fas fa-language'
            controller: 'Sitegeist\LostInTranslation\Controller\LostInTranslationModuleController'
            privilegeTarget: 'Sitegeist.LostInTranslation:AccessBackendModule'

    userInterface:
      translation:
        autoInclude:
          'Sitegeist.LostInTranslation':
            - Modules

  ContentRepositoryRegistry:
    presets:
      'default':
        commandHooks:
          'Sitegeist.LostInTranslation:TranslationCommandHook':
            factoryObjectName: Sitegeist\LostInTranslation\ContentRepository\CommandHook\TranslationCommandHookFactory
          'Sitegeist.LostInTranslation:SynchronizationCommandHook':
            factoryObjectName: Sitegeist\LostInTranslation\ContentRepository\CommandHook\SynchronizationCommandHookFactory
        # Activate for content governance mode:
        #authProvider:
        #  factoryObjectName: Sitegeist\LostInTranslation\ContentRepository\AuthProvider\AIAwareContentRepositoryAuthProviderFactory

        projections:
          'Sitegeist.LostInTranslation:StaleTranslations':
            factoryObjectName: Sitegeist\LostInTranslation\ContentRepository\StaleTranslationProjection\StaleTranslationProjectionFactory
