Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Sitegeist.LostInTranslation:Retranslation':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Sitegeist\LostInTranslation\Controller\RetranslationController'
